"""7

Revision ID: 148c3fc5d13b
Revises: 22420c092b6e
Create Date: 2024-06-28 17:52:16.437303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148c3fc5d13b'
down_revision: Union[str, None] = '22420c092b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_topics_form_id_forms', 'forms', ['form_id'], ['form_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
