"""6

Revision ID: 22420c092b6e
Revises: a1cc0c8bd554
Create Date: 2024-06-28 16:35:27.998801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22420c092b6e'
down_revision: Union[str, None] = 'a1cc0c8bd554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
