"""mass migration

Revision ID: 696253cdab28
Revises: 9a8590f5b4cc
Create Date: 2024-06-24 14:32:06.917776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696253cdab28'
down_revision: Union[str, None] = '9a8590f5b4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entries', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_form_entries_form_id_forms', 'forms', ['form_id'], ['form_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
