"""initial migrations

Revision ID: 90a43a7d90aa
Revises: 9cd382298802
Create Date: 2024-06-11 22:16:50.001667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a43a7d90aa'
down_revision: Union[str, None] = '9cd382298802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('title', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'description')
    op.drop_column('tickets', 'title')
    # ### end Alembic commands ###
