"""initial migrations

Revision ID: 9cd382298802
Revises: d3c84866bf69
Create Date: 2024-06-11 22:16:19.025912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd382298802'
down_revision: Union[str, None] = 'd3c84866bf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'description')
    op.drop_column('tickets', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('tickets', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
