"""5

Revision ID: a1cc0c8bd554
Revises: f1c563c4e70e
Create Date: 2024-06-28 16:29:35.592954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cc0c8bd554'
down_revision: Union[str, None] = 'f1c563c4e70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

       pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('thread_events', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('thread_entries', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('thread_collaborators', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('slas', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('form_values', schema=None) as batch_op:
        batch_op.alter_column('field_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('form_entries', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sla_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
