"""8

Revision ID: bf3853d86887
Revises: 148c3fc5d13b
Create Date: 2024-07-18 14:48:00.029342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3853d86887'
down_revision: Union[str, None] = '148c3fc5d13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_agents_dept_id_departments', 'departments', ['dept_id'], ['dept_id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_agents_role_id_roles', 'roles', ['role_id'], ['role_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('value')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
