"""4

Revision ID: f1c563c4e70e
Revises: b266b9c2b734
Create Date: 2024-06-26 18:35:47.160309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c563c4e70e'
down_revision: Union[str, None] = 'b266b9c2b734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ticket_priorities', ['priority_id'], ['priority_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'departments', ['dept_id'], ['dept_id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['topic_id'])
        batch_op.create_foreign_key(None, 'slas', ['sla_id'], ['sla_id'])
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['agent_id'])
        batch_op.create_foreign_key(None, 'ticket_statuses', ['status_id'], ['status_id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])

    # ### end Alembic commands ###
